added sections 10.7, 10.7.1,  10.5.2, 10.6, 10.6.1, 10.6.2
narrative-io/narrative-rfc pull request #2
Opened 2023-12-26 18:32 UTC by linehanMatt

added sections 10.7, 10.7.1,  10.5.2, 10.6, 10.6.1, 10.6.2, and REFRESH_SCHEDULE in 10.3.2.

Background https://narrative-io.slack.com/archives/D02T13H8ALC/p1703273937831759

2023-12-26 18:57 UTC, urbushey requested changes
Left some comments for some specific changes, thanks Matt!

2023-12-26 18:57 UTC, urbushey commented on nql.md
> +### 10.6 Querying via Access Rules
Let's refer to this every time as "Querying an Access Rule Directly" - including in the heading of this section.

2023-12-26 18:57 UTC, urbushey commented on nql.md
> +NQL supports querying internal or external access rules directly, in addition to the Rosetta Stone attribute catalog and dataset ids, through `_access_rule_id`.
`_access_rule_id` is confusing nomenclature, for two reasons:

1. because you use the term `id` but we actually want the user to understand that there are two identifiers the user can use: `id` (the numeric ID of the access rule) and `name` (the unique name/slug of the access rule) 
2. because we don't actually want the user to use an underscore before the name here (and in other parts of the query, we DO want them to use the underscore i.e. to refer to the Rosetta Stone attributes mapped on a dataset)

We should probably give examples of querying by both access rule name and access rule ID in at least one section below, but name querying should be preferred and used in the rest of the examples where you aren't explicitly demonstrating how to query the access rule by name or ID.

2023-12-26 18:57 UTC, urbushey commented on nql.md
> +An Access Rule ID, defined in section 5.1.2 as an identifier for the Access Rule that governs the query's permission, is added after the company identifier. When querying data in an external company
again, confusing example... the two examples we want to portray is that you can query the company's data, referring to the company by `company_slug`.

2023-12-26 18:57 UTC, urbushey commented on nql.md
> +An Access Rule ID, defined in section 5.1.2 as an identifier for the Access Rule that governs the query's permission, is added after the company identifier. When querying data in an external company
Is querying by actual company ID supported?

e.g.
`company_id`: 164
`company_name`: "Pickwell"
`access_rule_id`: 27

Can you write the query as:
```SELECT provider.idType FROM 164.27 provider```
?

2023-12-26 18:57 UTC, urbushey commented on nql.md
> +    - **`ds_identifier`**: Alias or identifier for the dataset.
Datasets have `id` and `unique_name` ... we should explicitly state that in the definition here.

2023-12-26 18:57 UTC, urbushey commented on nql.md
> +    - **`attribute_name`**: The name of the Rosetta Stone attribute to be mapped.
"to be mapped" -> "that is being selected? ?

2023-12-26 19:34 UTC, linehanMatt commented on nql.md
> +NQL supports querying internal or external access rules directly, in addition to the Rosetta Stone attribute catalog and dataset ids, through `_access_rule_id`.
querying by access_rule_id is not yet supported based on my conversation with Anton, we have to use the access rule's slug. I am updating section 5.1 to better explain the difference

2023-12-26 20:02 UTC, urbushey commented on nql.md
> +#### 5.1.4 `_source_company_slug`
if we add this here, i think it needs a (NOT YET IMPLEMENTED) flag.  The updates to NQL did not add this as far as I am aware, although we can now refer to company slugs and ids as well as access rule names in NQL directly.

e.g.

This is not supported yet:

```SELECT rosetta_stone.event_timestamp
FROM rosetta_stone
WHERE _access_rule_name = 'access_rule_1'
```

This is supported
```
SELECT 
   fanatics.access_rule_1.Team,
   fanatics.access_rule_1._rosetta_stone.event_timestamp
FROM
fanatics.access_rule_1
```

2023-12-26 20:02 UTC, urbushey commented on nql.md
> +#### 5.1.5 `_access_rule_name`
NOT YET IMPLEMENTED

2023-12-26 20:03 UTC, urbushey commented on nql.md
> +An access rule has two identifiers: a `name` and an `id`. NQL supports querying internal or external access rules directly, in addition to the Rosetta Stone attribute catalog and dataset ids, through
`_access_rule_name` is a specific identifier we will later add that will refer to the access rule names available to you. The underscore should not appear in this reference, since that is not the feature you are documenting here.

2023-12-26 20:05 UTC, urbushey commented on nql.md
> +An access rule name, defined in section 5.1.5 as a unique, human-readable name for a specific access rule in a company seat, is added after the company identifier. When querying data in an external c
_source_company_slug is not related to this feature, we should refer to it as `company_slug`.  update the examples as well...

e.g.
```
SELECT teams.baseball_teams
FROM sports_company.access_rule_unique_name_1 teams
```

2023-12-29 16:01 UTC, urbushey approved these changes
looks good!

2023-12-29 16:02 UTC, merged